development:
  adapter: mysql2
  encoding: utf8
  database: sample_rails_api_development
  pool: 5
  username: root
  password: 1
test:
  adapter: mysql2
  encoding: utf8
  database: sample_rails_api_test
  pool: 5
  username: root
  password: 1
production:
  adapter: mysql2
  encoding: utf8
  database: sample_rails_api_production
  pool: 5
  username: root
  password: 1
